#!/usr/bin/env bash
# This script checks the school file
if [ -e school ]; then echo "school file exists"; [ -s school ] && echo "school file is not empty" || echo "school file is empty"; [ -f school ] && echo "school is a regular file"; else echo "school file does not exist"; fi
